add_reactions = добавлять реакции
administrator = администратор
attach_files = прикреплять файлы
ban_members = банить
change_nickname = изменять никнейм
connect = подключаться
create_expressions = создавать выражения
create_forum_threads = создавать ветки
create_instant_invite = создавать приглашения
create_private_threads = создавать приватные ветки
create_public_threads = создавать ветки
deafen_members = выключать звук участников
embed_links = добавлять ссылки
external_emojis = использовать сторонние эмодзи
external_stickers = использовать сторонние эмодзи
kick_members = исключать
manage_channels = управлять каналами
manage_emojis = управлять эмодзи
manage_emojis_and_stickers
manage_events = управлять событиями
manage_expressions = управлять выражениями
manage_guild = управлять сервером
manage_guild_expressions =
manage_messages = управлять сообщениями
manage_nicknames = управлять никнеймами участников
manage_permissions = управлять правами
manage_roles = управлять ролями
manage_threads = управлять ветками
manage_webhooks = управлять вебхуками
mention_everyone = упоминать @everyone, @here и все роли
moderate_members = управлять участниками
move_members = перемещать участников
mute_members = выключать микрофон участникам
priority_speaker = приоритетный режим
read_message_history = читать историю сообщений
read_messages = читать сообщения
request_to_speak = поднимать руку
send_messages = отправлять сообщения
send_messages_in_threads = отправлять сообщения в ветки
send_tts_messages = отправлять TTS сообщения
send_voice_messages = отправлять голосовые сообщения
speak = говорить
start_embedded_activities = запускать активности
stream = стримить
use_application_commands = использовать команды
use_embedded_activities = использовать активности
use_external_emojis = использовать сторонние эмодзи
use_external_sounds = использовать сторонние звуки
use_external_stickers = использовать сторонние эмодзи
use_slash_commands = использовать слеш-команды
use_soundboard = использовать саунборд
use_voice_activation = использовать активацию по голосу
view_audit_log = смотреть журнал аудита
view_channel = смотреть канал
view_creator_monetization_analytics = смотреть статистику монетизации
view_guild_insights = смотреть статистику сервера
